5week-wenodev
CodeSoom/spring-week5-assignment-1 pull request #1
Opened 2021-02-22 00:18 UTC by wenodev

TODO-LIST 작성

2021-02-22 12:40 UTC, johngrib reviewed
오래간만입니다. 이번주도 힘내서 학습하기로 해요. 화이팅!

2021-02-22 16:33 UTC, wenodev commented
> 오래간만입니다. 이번주도 힘내서 학습하기로 해요. 화이팅!

네! 화이팅!

2021-02-23 08:36 UTC, wenodev commented
ProductControllerTest 코드를보면
update쪽에만 eq()를 사용한걸 볼 수 있습니다.

ex)
1. verify(productService).deleteProduct(1L);
2. verify(productService).updateProduct(eq(1L), any(ProductData.class));

1번과 2번을 각각 어떤 상황에서 사용하는건지 잘 모르겠습니다.

2021-02-23 12:21 UTC, johngrib requested changes
PR 대상이 `CodeSoom:main`으로 되어 있습니다. 
![image](https://user-images.githubusercontent.com/1855714/108842773-1eee6080-761d-11eb-903a-6560ce8d34b7.png)

PR 타이틀 가장 오른쪽에 있는 `Edit` 버튼을 클릭해서 PR 대상 브랜치를 변경해 주세요.

2021-02-23 12:34 UTC, johngrib commented
> ProductControllerTest 코드를보면
> update쪽에만 eq()를 사용한걸 볼 수 있습니다.
> 
> ex)
> 
> 1. verify(productService).deleteProduct(1L);
> 2. verify(productService).updateProduct(eq(1L), any(ProductData.class));
> 
> 1번과 2번을 각각 어떤 상황에서 사용하는건지 잘 모르겠습니다.

`eq`의 JavaDoc을 먼저 읽어보시면 어떨까요?

![image](https://user-images.githubusercontent.com/1855714/108843504-22361c00-761e-11eb-8a19-7443749e617e.png)

이번엔 `eq` 메소드가 정의된 `ArgumentMatchers.java` 파일의 클래스 JavaDoc을 읽어 봅시다. 아래 스크린샷입니다.

![image](https://user-images.githubusercontent.com/1855714/108843992-d172f300-761e-11eb-9d2a-3b9afba2a177.png)

2021-02-23 12:41 UTC, johngrib commented on app/build.gradle
> +    implementation 'com.github.dozermapper:dozer-core:6.4.0'
팀 동료를 위해, 새로 추가한 라이브러리에 대해 자신의 PR에 자신이 리뷰를 (제가 하고 있는 것처럼) 달아서 라이브러리의 도입 이유와 장/단점 공식 문서 등을 소개해 주세요.

2021-02-23 12:41 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/application/UserService.java
> + */
다음과 같이 하면 어떨까요?
```suggestion
/**
 * 사용자 비지니스 로직을 제공합니다.
 */
```

2021-02-23 12:41 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/application/UserService.java
> + * @Author wenodev
이건 요즘은 git 이 있어서 굳이 적지 않아도 됩니다.
```suggestion
```

2021-02-23 12:41 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/domain/User.java
> +import javax.persistence.*;
`import *`을 사용하지 않는 습관을 들이는 것이 좋습니다.

2021-02-23 12:41 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/UserServiceTest.java
> +}
마지막에 개행 문자를 추가해 주세요.

2021-02-23 12:41 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/domain/UserTest.java
> +}
마지막에 개행 문자를 추가해 주세요.

2021-02-23 12:41 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/domain/UserTest.java
> +                .email("email")
더미 값이긴 하지만 `dummy-test-email@codesoom.com` 처럼 형식을 갖춘 값을 넣는 것이 좋습니다.

2021-02-23 15:12 UTC, wenodev commented
> PR 대상이 `CodeSoom:main`으로 되어 있습니다.
> ![image](https://user-images.githubusercontent.com/1855714/108842773-1eee6080-761d-11eb-903a-6560ce8d34b7.png)
> 
> PR 타이틀 가장 오른쪽에 있는 `Edit` 버튼을 클릭해서 PR 대상 브랜치를 변경해 주세요.

변경했습니다!

2021-02-23 16:11 UTC, wenodev commented
> > ProductControllerTest 코드를보면
> > update쪽에만 eq()를 사용한걸 볼 수 있습니다.
> > ex)
> > 
> > 1. verify(productService).deleteProduct(1L);
> > 2. verify(productService).updateProduct(eq(1L), any(ProductData.class));
> > 
> > 1번과 2번을 각각 어떤 상황에서 사용하는건지 잘 모르겠습니다.
> 
> `eq`의 JavaDoc을 먼저 읽어보시면 어떨까요?
> 
> ![image](https://user-images.githubusercontent.com/1855714/108843504-22361c00-761e-11eb-8a19-7443749e617e.png)
> 
> 이번엔 `eq` 메소드가 정의된 `ArgumentMatchers.java` 파일의 클래스 JavaDoc을 읽어 봅시다. 아래 스크린샷입니다.
> 
> ![image](https://user-images.githubusercontent.com/1855714/108843992-d172f300-761e-11eb-9d2a-3b9afba2a177.png)
> 
> 그리고 마지막으로 `verify`의 주석을 읽어 봅시다.
> 
> ![image](https://user-images.githubusercontent.com/1855714/108844274-3b8b9800-761f-11eb-95f8-e2c5c8221ab0.png)

docs를 해석하며 차근차근 읽다보니 이유를 알겠네요. 감사합니다.
https://github.com/wenodev/TIL/blob/master/eq.md

2021-02-24 10:48 UTC, wenodev commented on app/build.gradle
> +    implementation 'com.github.dozermapper:dozer-core:6.4.0'
Entity와 DTO의 변환을 위해 Dozer라는 라이브러리를 사용하려고 합니다.
아래 링크의 글을 참조해주세요.
https://github.com/wenodev/TIL/blob/master/dozer.md

2021-02-24 12:33 UTC, johngrib commented on app/build.gradle
> +    implementation 'com.github.dozermapper:dozer-core:6.4.0'
잘 읽었습니다! 이렇게 새로운 라이브러리를 추가할 때 PR에서 소개해준다면 동료들이 PR을 검토할 때 큰 도움이 될 거에요!

2021-02-24 13:07 UTC, johngrib reviewed
이번 한 주간 커밋 메시지를 영어로 적지 않고 한국어로 적어서 커밋을 해 보세요. 저와 함께 커밋 메시지도 바람직하게 적는 연습을 해 봅시다. 커밋 메시지를 잘 적을 수 있게 되면, 그 이후에 영어로 적는 연습을 따로 해 보셔도 좋을 거에요.

2021-02-24 13:07 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/application/UserService.java
> + * 사용자 비지니스 로직을 제공합니다.
변경은 잘 하셨는데요, 커밋 메시지에 오타가 있습니다. `UserService javadoc @Authro 제거` 이제부터는 커밋 메시지도 지켜볼 것입니다 😎

2021-02-24 13:07 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/UserServiceTest.java
> +        User user = userService.getUser();
이렇게 하면 위에 선언한 `user`에 할당하지 못할 것 같아요.

2021-02-24 13:07 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/UserNotFoundException.java
> +}
마지막에 개행 문자를 추가해 주세요.

2021-02-24 13:07 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/UserServiceTest.java
> +    void getUserWithNotExistedId(){
`@DisplayName`으로 테스트에 설명을 추가해 주세요.

2021-02-25 12:51 UTC, johngrib reviewed
새로 올려주신 커밋 메시지가 작업 내용을 충분히 표현하지 못하고 있습니다.

2021-02-25 12:51 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/dto/UserRequestDto.java
> +import lombok.*;
`import *`을 지양해 주세요.

2021-02-25 12:54 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/dto/UserRequestDto.java
> +@Setter
클래스에 붙이는 `@Setter`에 대해서는 PR에 자기 자신의 리뷰를 달아서 동료들을 설득해야 합니다.

2021-02-25 12:54 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/UserServiceTest.java
> + */
너무 잘 하고 계셔서 리뷰 레벨을 조금만 더 높이겠습니다! 오늘부터는 할 일을 관리하는 주석은 클래스 바깥에서 하거나, 주석 내에 `TODO` 태그를 달아 주세요.

2021-02-26 12:26 UTC, johngrib reviewed
a8154ad33282a538355b5b17da099b93c1f149a8 커밋의 메시지가 아쉽습니다. 
커밋 메시지는 `[test] update 메소드를 성공하는 코드` 인데요, 커밋에 포함된 작업은 `updateUser` 시그니처였어요. `[test]`가 있어서 테스트 코드가 있을 거라 생각했는데 제 기대와 달리 테스트 코드는 없었습니다.

2021-02-26 12:26 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/UserServiceTest.java
> +
불필요한 공백 라인입니다. 커밋하기 전에 커밋할 파일들을 하나하나 살펴보는 연습을 해보는 것도 좋겠습니다.

2021-02-26 12:29 UTC, johngrib reviewed
이 커밋 메시지를 다음과 같이 수정하면 어떨까요?
`[test] 존재하지 않는 유저 예외를 테스트` 

제 취향은 명령형으로 커밋 메시지를 작성하는 건데요, 다음과 같이 적습니다.
`[test] "존재하지 않는 유저 예외"를 테스트하라`

2021-02-26 12:29 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/application/UserService.java
> +        return null;
커밋 단위가 너무 작지는 않았는지요? 또는 커밋 메시지가 지나치게 짧은 것은 아닐까요?

2021-02-26 12:31 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/UserServiceTest.java
> +        assertThatThrownBy(()-> userService.delete(1000L))
`1000L`로 바꾼 이유는 무엇인가요? 커밋 메시지에서 그것을 설명할 수 있으면 좋겠습니다. 커밋 타이틀과 커밋 본문 메시지를 적절히 수정해 보세요.

2021-02-26 12:31 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/controllers/UserControllerTest.java
> +}
파일 마지막에 개행 문자를 추가해 주세요.

2021-02-26 19:33 UTC, wenodev commented on app/src/main/java/com/codesoom/assignment/dto/UserRequestDto.java
> +import lombok.*;
넵!

2021-02-26 19:34 UTC, wenodev commented on app/src/main/java/com/codesoom/assignment/dto/UserRequestDto.java
> +@Setter
Setter가 필요 없다고 판단하여 삭제했습니다.
어디선가" DTO는 Getter와 Setter만 사용해라" 라는 말을 봐서 무의식 중에 Setter를 사용한 것 같네요.
코드를 작성할 때 확실한 근거를 가지고 작성하는 습관을 가져야겠습니다.

2021-02-26 19:37 UTC, wenodev commented on app/src/main/java/com/codesoom/assignment/domain/User.java
> +import javax.persistence.*;
넵!

2021-02-28 12:09 UTC, johngrib reviewed
한 주간 고생 많으셨습니다. 주간 회고를 작성해 공유해 주세요.

2021-03-01 23:10 UTC, wenodev commented
> 한 주간 고생 많으셨습니다. 주간 회고를 작성해 공유해 주세요.

넵!

2021-03-03 12:16 UTC, merged