5주차 과제 제출
CodeSoom/spring-week5-assignment-1 pull request #28
Opened 2021-09-06 10:16 UTC by injoon2019

안녕하세요

우선 강의는 수강하였고, 4주차 코드를 이전하였습니다.

2021-09-06 12:34 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/controller/CatToyController.java
> +public class CatToyController {
클래스 이름 `CatToyController`가 아쉽습니다. 처음엔 `CatToy`만 팔고 있지만, 사업이 잘 되면 `CatFood`도 팔 수 있고, `CatSand`도 팔고, `DogToy`도 팔고... 계속 확장이 될 수 있겠죠. 확장에 열려 있는 추상화된 이름을 사용하는 것이 좋을 거에요. `Cat` 대신 `Product` 같은 이름을 쓰는 것도 방법이겠죠.

2021-09-06 12:34 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/service/CatToyService.java
> +}
이 인터페이스를 두고 생각해 봅시다. 이 인터페이스는 `CatToy`라는 이름을 갖고 있기 때문에 범용성이 떨어집니다. 이 인터페이스의 구현체가 몇 개까지 늘어나게 될까요? 1개에서 그치지 않을까요?

2021-09-06 12:34 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/service/CatToyServiceTest.java
> +        }
이 테스트에서 `verify` 구문은 테스트의 목표와 관계가 없어요. 이 테스트의 목표는 `getCatToys`메소드가 장난감 목록 전체를 반환하는 것인지 확인하는 것인데요, 여기에서는 `catToyRepository`를 필요 이상으로 강하게 의식하고 있습니다. `catToyRepository`가 `animalToyRepository`로 변경된다 하더라도 이 테스트는 실패하지 않도록 느슨하게 연결해주는 것이 바람직합니다.

2021-09-06 12:34 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/service/CatToyServiceTest.java
> +            verify(catToyRepository).findById(EXIST_ID);
이 테스트 파일에 있는 모든 메소드에서 `verify`가 있는 행은 불필요해 보여요. 모두 지워주셔도 괜찮겠어요.

2021-09-06 12:34 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/service/CatToyServiceTest.java
> +        }
테스트 메시지와 테스트 내용이 미묘한 차이가 있습니다. 테스트 내용을 읽어보면 테스트 메시지가 다음과 같이 수정되어야 할 것 같아요.

`요청된 장난감을 삭제한다.` => `catToyRepository에 장난감 삭제를 요청한다.`

왜냐하면 여기에서 검증하고 있는 것이 테스트 주인공인 `deleteCatToyById`가 아니라 `catToyRepository`의 어떤 어떤 메소드가 호출되었는지이기 때문이에요. 그래서 이 테스트는 본질에서 멀어졌습니다. 어떻게 수정해야 좋을까요?

2021-09-07 04:45 UTC, injoon2019 commented on app/src/main/java/com/codesoom/assignment/controller/CatToyController.java
> +public class CatToyController {
그렇네요

그러면 만약 사업이 확장되면 ```CatToy```외에 ```CatSand```나 ```DogToy```가 추가되면 컨트롤러는 그대로 두고 URI를 바꿔서 매핑되는 것을 식별하면 될까요?

2021-09-07 04:47 UTC, injoon2019 commented on app/src/main/java/com/codesoom/assignment/service/CatToyService.java
> +}
맞습니다. ```ProductService```로 수정하였습니다.

2021-09-07 04:50 UTC, injoon2019 commented on app/src/test/java/com/codesoom/assignment/service/CatToyServiceTest.java
> +            verify(catToyRepository).findById(EXIST_ID);
넵 수정하였습니다

2021-09-07 04:53 UTC, injoon2019 commented on app/src/test/java/com/codesoom/assignment/service/CatToyServiceTest.java
> +        }
넵 지나치게 강하게 연결되어있다는 점 이해했습니다! 궁금한 것이 있는데 ```Controller```의 목적은 매핑되는 ```Service```의 메서드를 호출하는 것이라고 생각했거든요 그래서 강의에서 ```Controller```에서 ```Service```의 메서드를 호출하는지 ```verify```하더라고요.

그렇다면 ```Service```의 목적은 ```Repository```의 메서드를 호출하는 것 아닌가요? (만약 ```Repository```가 있고, 필요한 경우라는 전제하에). 그렇다면 ```verify```가 필요한 것 같기도하고 아닌 것 같기도해서 헷갈리네요

2021-09-07 04:57 UTC, injoon2019 commented on app/src/test/java/com/codesoom/assignment/service/CatToyServiceTest.java
> +        }
두 가지 방법이 있는데, [여기](https://github.com/CodeSoom/spring-week5-assignment-1/pull/28#discussion_r703174653)에서와 비슷하게 지금 제가 이해한 것으로는 ```Controller```의 역할은 알맞은 ```Service```에 요청을 보내는 것에서 끝이나는 것이고 (이후의 역할은 ```Service```의 책임이 된다고 생각하였습니다) , ```Serivce```의 역할은 ```Repository```가 존재하고, 필요한 경우라면 ```Repository```에 요청을 보내는 것 같습니다. 

그래서 두 가지 방법 중 
```요청된 장난감을 삭제한다.``` => ```catToyRepository에 장난감 삭제를 요청한다.```
이게 더 맞는 것 같다는 생각이 드네요. 취향의 문제인가요, 아니면 정답이 있는 문제인가요??

2021-09-07 08:33 UTC, injoon2019 commented
이번에 추가된 라이브러리들이 있어서 간단하게나마 설명을 드리고자 합니다.

1. Lombok
보일러 플레이트 코드를 줄여 줄 수 있는 라이브러리입니다. 단순 반복되는 코드양을 어노테이션을 붙여주는 것으로 해결 할 수 있습니다. 예를 들어, getter, setter의 경우 각 함수를 만들지 않고 @Getter, @Setter를 붙여줌으로서 동일한 결과가 나옵니다.
[Lombok 공식 문서](https://objectcomputing.com/resources/publications/sett/january-2010-reducing-boilerplate-code-with-project-lombok)

2. Spring Validation
데이터에 대한 검증을 제공하는 라이브러리입니다. 애노테이션으로 편하게 사용이 가능하며, 직접 ```Validator```를 만들지 않아도 되는 장점이 있습니다.

[Spring Validation 공식 문서](https://docs.spring.io/spring-framework/docs/3.2.x/spring-framework-reference/html/validation.html)

2021-09-07 12:11 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/controller/CatToyController.java
> +public class CatToyController {
보통 쇼핑몰에서는 그런 식으로 작업하진 않아요. `CatToy`가 되었건 `CatSand`가 되었건 고객에게 판매할 물건이라는 특성만 남겨둡니다. 즉 추상화해서 `Product`로 만들고, 추상화 단계에서 제품 특성은 `Product`가 갖는 값들 중 하나로 녹여버리죠. 그렇게 된다면 여기에서 말하는 `CatToy`니 `DogFood`니 하는 것들은 `Category`가 됩니다. 카테고리 클래스의 `String name` 같은 값으로 들어가게 되는 방식이 흔합니다.

2021-09-07 12:29 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/service/CatToyServiceTest.java
> +        }
앗 조심해야 해요. `Service.getCatToys()`의 목적은 `Repository.findAll()`의 메소드를 호출하는 것이 아니에요.
(`@DisplayName`에 `Service.getCatToys()`의 목적은 `장난감 목록 전체를 반환하는 것`이라고 직접 작성하셨죠.)

`Repository`는 수단입니다. 인준님이 아침에 집을 나와서 회사에 간다고 생각해 봅시다. 그리고 인준님의 목표가 회사에 도착하는 거라고 합시다. 그런데 제가 인준님이 지하철을 탑승하는 것만 보고 "아 인준님은 회사에 도착했어"라고 생각한다면 이건 논리의 비약이 됩니다. 

여기에서 중요한건 인준님이 지하철을 타는 것 외에 회사에 가는 방법이 다양하다는 거에요. 만약 인준님이 이직을 해서 걸어서 다닐 수 있는 곳으로 회사가 바뀌었다면, 제가 인준님이 이제 지하철을 안 타니까 회사에 매일 결근하는구나 라고 생각하면 안 되겠죠.

`CatToyService`에서 `CatToyRepository`의 참조는 지금은 필수적인 것처럼 보이지만, 리포지토리의 무슨 메소드를 어떻게 호출하는지를 체크하는 것은 별로 의미가 없습니다. 중요한 것은 "장난감 목록 전체가 정말로 반환되는지"에요.

2021-09-07 12:43 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/service/CatToyServiceTest.java
> +        }
> 그래서 두 가지 방법 중
> `요청된 장난감을 삭제한다.` => `catToyRepository에 장난감 삭제를 요청한다.`
> 이게 더 맞는 것 같다는 생각이 드네요. 취향의 문제인가요, 아니면 정답이 있는 문제인가요??

정답은 없어요. 그렇게 해도 괜찮습니다. 특히 `catToyRepository에 삭제를 요청`하는 것은 메시징이므로 객체지향 관점에서 적절한 설명처럼 보일 수도 있습니다. 그런데 여기에서 중요한 것이 있어요. 이렇게 설명해버리면 리포지토리와 서비스 사이에 커플링이 생깁니다.

서비스는 수단과 방법을 가리지 않고 장난감을 삭제하는 녀석이어야 해요. 지금은 로직이 단순해서 리포지토리에 대한 의존이 당연해 보이는 것입니다.

이런 경우를 생각해 봅시다. 지금의 `deleteCatToyById` 메소드는 리포지토리의 `deleteById`를 부르기만 할 뿐인 심심한 녀석입니다.
그런데 서비스 로직이 많이 바뀌었다고 합시다. DB에 장애가 자주 발생하게 되었거나 해서 장애에 대한 대비책이 추가되었다고 생각해 봐요. 이제 `deleteCatToyById`를 호출하면 리포지토리의 `deleteById`를 그냥 부르지 않습니다. `deleteCatToyById`는 다음과 같은 과정을 거치게 수정되었습니다.

1. 상품이 삭제된다는 사실을 담당자들에게 카카오톡으로 알려줍니다.
2. 상품 삭제의 실패를 대비하기 위해 `deletePrepareRepository`에 삭제할 정보를 기록합니다.
3. `catToyRepository`에 있는 `deleteById`를 호출해 상품 삭제를 시도합니다.
4. DB에 장애가 발생해 상품 삭제가 실패했다면, 1초 후에 `deletePrepareRepository`에 저장된 정보를 조회해 와서 3으로 돌아가 재시도합니다.
5. 실패하면 2초 후에 재시도합니다.
6. 실패하면 4초 후에 재시도합니다.
7. 또 실패하면 `deleteCandidateRepository`에 삭제할 정보를 기록합니다.
8. 이후의 로직...

만약 "요청된 장난감을 삭제한다"로만 작성했다면 로직이 이렇게 바뀌어도 설명을 수정하지 않아도 괜찮겠죠. 하지만 `catToyRepository`를 설명에 바인딩시켜버리면 로직이 바뀔 때마다 설명도 바꾸어야 할 수도 있습니다.

2021-09-08 08:13 UTC, injoon2019 commented on app/src/test/java/com/codesoom/assignment/service/CatToyServiceTest.java
> +        }
리포지토리와 무관하게 실제 요청된 서비스를 실행하는 것이 목적이라는 것을 이해했습니다!

```verify```를 안쓰고 테스트 코드 작성을 한 번 해보도록 하겠습니다

2021-09-08 08:19 UTC, injoon2019 commented on app/src/test/java/com/codesoom/assignment/service/CatToyServiceTest.java
> +        }
위의 설명과 이 설명을 함께 읽으니 이해가 잘되네요!

서비스는 서비스에서 로직을 끝내야하는게 목적이네요 ㅎㅎ 한번 수정을 해보도록하겠습니다.

2021-09-08 09:03 UTC, injoon2019 commented on app/src/test/java/com/codesoom/assignment/service/ProductServiceTest.java
> +        void deleteCatToyByExistedId() {
삭제에 대한 테스트는 어떻게 해야 좋을까요? given()에 삭제에 관한 것을 추가하려했더니 안되는데 다른 방법이 있는걸까요?

2021-09-08 13:35 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/service/ProductServiceTest.java
> +        void deleteCatToyByExistedId() {
지금은 `given`에 익숙해지는 게 중요한 게 아니니까, 그냥 삭제한 다음에 조회가 되는지 확인해 보세요. `given`은 나중에 테스트의 논리에 익숙해진 다음에 사용해 봅시다.

2021-09-08 13:46 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/product/controller/ProductController.java
> +public class ProductController {
3줄의 불일치가 눈에 띕니다.

- `CatToy에 대한 HTTP 요청 처리를 담당한다.`
- `@RequestMapping("/products")`
- `public class ProductController {`

이미 `CatToy`를 `Product`로 추상화한 개념으로 클래스 명명과 URL 디자인에 적용하셨어요. `CatToy`라는 이름은 아예 모두 삭제하고 `Product`만 남겨놔도 괜찮습니다.

2021-09-08 13:46 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/product/domain/CatToy.java
> +@NoArgsConstructor
`@AllArgsConstructor`는 위험한 애노테이션으로 유명합니다. 이걸 금지하는 회사도 많아요. 그 이유에 대해 조사해 보시고 여기에 설명도 해 보세요.

2021-09-08 13:46 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/product/service/ProductService.java
> +}
이 인터페이스의 모든 메소드에 javadoc 주석을 작성해 보세요. 구현체가 javadoc을 상속하게 됩니다.

2021-09-08 13:46 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/product/service/ProductServiceImpl.java
> +        CatToy foundCatToy = catToyRepository.findById(id).orElseThrow(CatToyNotFoundException::new);
적절히 개행해서 한 줄이 `.`이 한 개만 오게 해 주세요.

2021-09-08 13:46 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/product/service/ProductServiceTest.java
> +            Assertions.assertThat(catToys).hasSize(1);
여기에 `1`이 오면 안 됩니다. 여기에 `1`이 있어야 할 논리적인 근거가 없어요. 이 논리적인 근거는 이 `1`을 써놓은 사람의 머리 속에만 있습니다. `1`의 근거를 코드를 통해 마련해 주어야 합니다. 근거가 마련되면 이 파일에서 `1`은 사라지겠지요.

```suggestion
            Assertions.assertThat(catToys).hasSize( ... );
```

2021-09-08 13:46 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/product/service/ProductServiceTest.java
> +    private static final Long NOT_EXIST_ID = 100L;
이 두 값에 논리적인 근거가 없습니다.

2021-09-09 10:06 UTC, injoon2019 commented on app/src/test/java/com/codesoom/assignment/service/ProductServiceTest.java
> +        void deleteCatToyByExistedId() {
``` java
        @Test
        @DisplayName("존재하는 식별자일 때 요청된 장난감을 삭제한다.")
        void deleteCatToyByExistedId() {
            productService.deleteCatToyById(EXIST_ID);
            assertThatThrownBy(() -> productService.findCatToyById(EXIST_ID))
                    .isInstanceOf(CatToyNotFoundException.class);
        }
```
여기서 ```EXIST_ID```에 해당하는 제품을 삭제하고, 다시 ```findCatToyById```를 하면 예외가 발생한다라고 하였는데요예외가 발생하지 않고 있습니다. ```deleteCatToyById```를 호출했을 때, ```repository```에서 삭제가 일어나게  ```given```에서 삭제와 관련된 설정을 해줘야하는 것 아닌가요?

2021-09-09 10:11 UTC, injoon2019 commented on app/src/main/java/com/codesoom/assignment/product/controller/ProductController.java
> +public class ProductController {
넵 ```product```로 수정하였습니다.

이 경우 아예 ```Product```라는 ```CatToy```의 부모 클래스를 만들어서 코드상에서도 Product만 주고 받고 하는게 더 나을까요? 아니면 그건 읽을 때 명확성이 떨어지게 되나요?

2021-09-09 10:13 UTC, injoon2019 commented on app/src/main/java/com/codesoom/assignment/product/service/ProductServiceImpl.java
> +        CatToy foundCatToy = catToyRepository.findById(id).orElseThrow(CatToyNotFoundException::new);
넵 수정하였습니다!

2021-09-09 10:32 UTC, injoon2019 commented on app/src/main/java/com/codesoom/assignment/product/domain/CatToy.java
> +@NoArgsConstructor
https://lkhlkh23.tistory.com/159 
https://github.com/CodeSoom/spring-week4-assignment-1/pull/32#discussion_r702253071
참고한 곳들 출처입니다!

블로그 글의 제목이 인상 깊었습니다. "Lombok 너무 편리하기 때문에 주의해야 한다."
 
```AllArgsConstructor```와 ```RequiredArgsConstructor```를 조심해야하는데, ```AllArgsConstructor```는 말 그대로 객체 내부 모든 인스턴스 멤버를 가지고 있는 생성자를 만드는 애노테이션이고, ```RequiredArgsContructor```는 final, NotNull이 붙은 인스턴스 멤버들을 가지는 생성자를 만드는 것입니다. 

하지만 이렇게 되면, 객체를 생성할 때 파라미터의 순서에서 실수할 확률이 커지게 됩니다.
```lastName```과 ```firstName```을 ```String```으로 가진다면

``` java
Person person = new Person("Son", "Injun");
```
에서 순서를 잘못 넣는다면 오류가 발생하게 됩니다. 

빌더 패턴을 사용한다면 이러한 실수를 줄일 수 있을 것 같습니다.

2021-09-09 10:56 UTC, injoon2019 commented on app/src/test/java/com/codesoom/assignment/product/service/ProductServiceTest.java
> +            Assertions.assertThat(catToys).hasSize(1);
그렇네요 반환 받은 리스트의 크기와, 처음에 만든 리스트의 크기가 같다는 것을 테스트하도록 하였습니다.

2021-09-09 11:04 UTC, injoon2019 commented on app/src/test/java/com/codesoom/assignment/product/service/ProductServiceTest.java
> +    private static final Long NOT_EXIST_ID = 100L;
```EXIST_ID```의 경우에는 실제로 추가했던 ```CatToy```에서 ```getId```로 정해줘서 근거가 생긴 것 같습니다.
```NOT_EXIST_ID```의 경우에는 우선은 ```EXIST_ID```의 값 + 100을 해놨는데, 어떻게 강한 근거를 만들어야할지 안떠오르네요

2021-09-09 12:38 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/product/controller/ProductController.java
> +public class ProductController {
아니오. `CatToy`라는 단어 자체가 이 프로젝트 전체에서 전혀 필요가 없어요. 과제 이름에 속으면 안 됩니다. `Product`만 남기는 것이 좋습니다. 오늘은 CatToy를 팔고 있지만 내일 CatToy가 다 떨어져서 DogToy를 팔기 시작했다고 생각해 봅시다. "고양이 장난감 가게"는 소프트웨어 입장에서는 그냥 가게 이름일 뿐인 거에요. 더 많은 종류의 상품을 팔 수 있도록 추상화를 완료한 코드가 더 많은 상품을 팔 수 있을 정도로 유연하고 더 유지보수하기 좋은 상점이 되는 거죠.

2021-09-09 12:41 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/product/service/ProductServiceTest.java
> +    private static final Long NOT_EXIST_ID = 100L;
`NOT_EXIST_ID`를 만드는 논리적인 방법은 두 가지가 있습니다.

1. `NOT_EXIST_ID`를 사용하기 전에 `NOT_EXIST_ID`로 상품을 찾아 지워버립니다.
2. `NOT_EXIST_ID`를 사용하기 전에 모든 상품을 지웁니다.

이렇게 하면 확실히 `NOT_EXIST_ID`는 존재하지 않는 아이디가 되겠죠.
테스트에서 가장 중요한 것은 논리입니다. 그 외의 모든 것은 이 논리를 돕기 위한 도구입니다.

2021-09-09 12:46 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/service/ProductServiceTest.java
> +        void deleteCatToyByExistedId() {
여기를 봅시다. 

![image](https://user-images.githubusercontent.com/1855714/132687829-513532c2-a99e-462e-ad72-535eaf1679fc.png)

여기도 봅시다.

![image](https://user-images.githubusercontent.com/1855714/132688069-a8cdd0de-8b18-4ab4-a63f-d0a0d21aaf31.png)

`given`은 괜찮은 도구이지만, 처음에 테스트를 배울 때에는 `given`을 아예 쓰지 않고 배우는 것이 좋습니다. 지금 `given`의 사용 때문에 테스트의 논리와 흐름이 모두 영향을 받고 있어요. 지금 익혀야 하는 것은 `given`을 어떻게 사용하는지가 아닙니다. 그건 하나도 안 중요해요. 테스트와 논리를 배우는 것이 지금 해야 할 일이에요. 지금 테스트에서 `given`을 모두 삭제하고 다시 작성해 보세요.

2021-09-10 09:48 UTC, injoon2019 commented on app/src/main/java/com/codesoom/assignment/product/service/ProductService.java
> +}
넵 javadoc 작성하였습니다!

2021-09-10 09:49 UTC, injoon2019 commented on app/src/main/java/com/codesoom/assignment/product/controller/ProductController.java
> +public class ProductController {
이해했습니다! ```CatToy```를 ```Product```로 수정하였습니다.

2021-09-10 10:55 UTC, injoon2019 commented on tests/__tests__/user.spec.js
>    describe('PATCH /users/{id}', () => {
정삭적인 데이터가 들어와야하는데 Invalid 데이터가 들어오는 상황인 것 같아 테스트코드 수정하였습니다.

2021-09-10 10:55 UTC, injoon2019 commented on tests/__tests__/user.spec.js
>      };
정상적인 데이터가 들어와야하는데 invalid한 데이터가 들어오고 있어 테스트 코드 수정하였습니다.

2021-09-10 10:56 UTC, injoon2019 commented on app/src/test/java/com/codesoom/assignment/product/service/ProductServiceTest.java
> +    private static final Long NOT_EXIST_ID = 100L;
넵 이해했습니다!

2021-09-10 10:56 UTC, injoon2019 commented on app/src/test/java/com/codesoom/assignment/service/ProductServiceTest.java
> +        void deleteCatToyByExistedId() {
넵 Dto 구현이 밀려있어서 그것 구현하고 바로 해보도록 하겠습니다!

2021-09-10 12:40 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/product/domain/CatToy.java
> +@NoArgsConstructor
잘 조사하셨지만 꼭 롬복 공식 홈페이지도 조사해보세요. 항상 공식 문서를 보는 습관을 기르셔야 합니다.

2021-09-10 12:45 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/product/domain/Product.java
> +
```suggestion
```

2021-09-10 12:45 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/product/domain/Product.java
> +@Builder
`@Builder`를 `class` 선언 바로 위에 선언하는 것은 안티패턴입니다. `@Builder`를 올바르게 사용하는 방법에 대해 조사해서 설명해 보세요.

2021-09-10 12:45 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/product/exception/ProductNotFoundException.java
> +    }
예외를 던질 때 메시지를 담을 수 있도록 고쳐 보세요.

2021-09-10 12:45 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/product/repository/ProductRepository.java
> +public interface ProductRepository extends CrudRepository<Product, Long> {
이 인터페이스와 모든 메소드에 javadoc 주석을 작성해 보세요. 인터페이스 구현체에도 javadoc 메소드는 상속이 됩니다.

2021-09-10 12:45 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/product/service/ProductService.java
> +    Product findProductById(Long id);
혹시 인터페이스에서 선언하지 않은 예외를 구현체에서 멋대로 던지고 있지는 않은가요?
```suggestion
    /**
     * 식별자와 일치하는 제품을 반환한다
     * @param id 제품 식별자
     * @return 제품
     */
    Optional<Product> findProductById(Long id);
```

2021-09-12 02:15 UTC, injoon2019 commented on app/src/main/java/com/codesoom/assignment/product/domain/CatToy.java
> +@NoArgsConstructor
넵 알겠습니다!

[공식 문서](https://projectlombok.org/features/constructor) 확인을 해보았습니다.

```
@AllArgsConstructor generates a constructor with 1 parameter for each field in your class. Fields marked with @NonNull result in null checks on those parameters.
```
하나의 파라미터가 각 필드에 대응이되네요

2021-09-12 02:30 UTC, injoon2019 commented on app/src/main/java/com/codesoom/assignment/product/exception/ProductNotFoundException.java
> +    }
넵 수정하였습니다!

2021-09-12 02:40 UTC, injoon2019 commented on app/src/main/java/com/codesoom/assignment/product/service/ProductService.java
> +    Product findProductById(Long id);
앗 그렇네요

이 부분에서 반환 값에 전부(Service, Controller) ```Optional```을 씌워주라는 말씀이신가요 아니면 인터페이스에 예외 선언을 하라는 말씀이신가요??

만약 인터페이스에서 
``` java
Product findProductById(Long id) throws ProductNotFoundException;
```
이런식으로 하면 Optional로 감싼 객체가 아닌 그냥 Product를 반환해도 되는걸까요?

2021-09-12 02:51 UTC, injoon2019 commented on app/src/main/java/com/codesoom/assignment/product/repository/ProductRepository.java
> +public interface ProductRepository extends CrudRepository<Product, Long> {
넵 작성해보았습니다. ```ProductService```의 Javadoc과 상당히 비슷해서 혹시 뭔가를 놓치고 있는건 아닌가 하는데 괜찮나요?

2021-09-12 03:24 UTC, injoon2019 commented
```DozerMapper```라는 라이브러리를 사용하여 설명을 드리고자 합니다.

```
implementation 'com.github.dozermapper:dozer-core:6.4.0'
```
매핑 프레임워크는 레이어드 아키텍쳐에서 유용합니다. 계층간 이동을 할 때 데이터를 캡슐화하여 보낼 수 있기 때문입니다. 라이브러리를 사용함으로서 일일이 코드로 데이터를 옮기던 것을 간편하게 할 수 있기 때문입니다.

``` java
public class ProductData {
    private Long id;

    @NotBlank
    @Mapping("name")
    private String name;

    @NotBlank
    @Mapping("maker")
    private String maker;

    @NotNull
    @Mapping("price")
    private Integer price;

    private String imageUrl;
}
```
``` java
Product product = mapper.map(productData, Product.class);
```
이런식으로 Product의 Dto인 ProductData에서 Product로 간편하게 매핑을 할 수 있습니다. 


[DozerMapper Github](https://github.com/DozerMapper/dozer)

2021-09-12 12:07 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/product/repository/ProductRepository.java
> +public interface ProductRepository extends CrudRepository<Product, Long> {
지금 `ProductService`가 하는 일이 너무 많아서 데이터 입출력을 담당하고 있는 `ProductRepository`와 하는 일이 똑같아 보이는 구조 문제가 있습니다. 인준님은 그걸 알아차리신 거고요. `ProductService`를 여러개로 쪼개서 만들어보시길 권해드려요. (`Service`라는 이름이 클래스에 안 들어가는 것이 좋습니다.)

2021-09-12 12:09 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/product/service/ProductService.java
> +    Product findProductById(Long id);
이 메소드 이름을 두고 잘 생각해 봅시다. 이건 아이디를 통해 상품을 검색하는 메소드라 생각할 수 있어요. 웹 브라우저에서 뭔가 검색했을 때 검색 결과가 안 나오면 보통 어떻게 되나요? 예외가 발생하면서 웹 브라우저가 종료될까요? 검색 결과가 없다면 없는 상태로 리턴해주는 것도 괜찮은 방법입니다. 예외는 조심스럽게, 예외적으로 사용하는 것이 바람직합니다. 예외를 제어 수단으로 남용하는 것이 좋지 않다는 것을 염두에 두고 항상 예외를 최소화하면서 코딩하는 습관을 길러보세요. (물론 예외보다 null을 리턴하는 것이 일반적으로 더 안 좋은 방법입니다.)

2021-09-12 12:10 UTC, johngrib reviewed
일요일에는 주간 회고를 작성해 슬랙에 공유해주세요.
한 주간 고생 많으셨습니다. 한 주간 쑥쑥 성장하시는 것이 보여 기뻤습니다.

2021-09-12 13:01 UTC, johngrib requested changes
PR 타깃이 `CodeSoom:main`으로 되어 있습니다. `Edit` 버튼으로 수정해 주세요.
![image](https://user-images.githubusercontent.com/1855714/132988534-ae73c5e4-a2f6-4d93-988c-8a5b427cb63a.png)

2021-09-12 14:32 UTC, injoon2019 commented on tests/__tests__/user.spec.js
>      };
넵 이번주에는 못했지만 해보겠습니다

2021-09-12 14:34 UTC, injoon2019 commented on app/src/main/java/com/codesoom/assignment/product/service/ProductService.java
> +    Product findProductById(Long id);
이해 했습니다!

2021-09-12 14:35 UTC, injoon2019 commented on app/src/main/java/com/codesoom/assignment/product/repository/ProductRepository.java
> +public interface ProductRepository extends CrudRepository<Product, Long> {
어렵네요! ```ProductService``` 안에는 이미 메서드들로 나누어져있는데 어느 범위까지 더 나눠야할지 정하는게 어렵네요

2021-09-12 14:44 UTC, injoon2019 commented on app/src/main/java/com/codesoom/assignment/product/domain/Product.java
> +@Builder
넵 이번주에는 못했지만 해보겠습니다

2021-09-12 23:03 UTC, merged