[Week 5] 고양이 장난감 가게 만들기 - 심화
CodeSoom/spring-week5-assignment-1 pull request #7
Opened 2021-02-22 15:19 UTC by yhyojoo

### 1. 고양이 장난감가게 유효성 검사 추가하기

> - [ ] 고양이 장난감 목록 얻기 - GET /products
> - [ ] 고양이 장난감 상세 조회하기 - GET /products/{id}
> - [ ] 고양이 장난감 등록하기 - POST /products
> - [ ] 고양이 장난감 수정하기 - PATCH /products/{id}
> - [ ] 고양이 장난감 삭제하기 - DELETE /products/{id}

### 2. 회원 관리하기

> - [ ] 회원 생성하기 - POST /user
> - [ ] 회원 수정하기 - POST /user/{id}
> - [ ] 회원 삭제하기 - DELETE /user/{id}

안녕하세요! 한 주간 잘 부탁드립니다 😁

2021-02-23 12:08 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/domain/Product.java
> +import lombok.*;
`import *`은 좋지 않은 습관입니다.

2021-02-23 12:08 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/domain/Product.java
>  @AllArgsConstructor
`@AllArgsConstructor` 사용을 자제하는 것이 좋습니다. 인터넷에서 이 애노테이션이 어떤 점이 안 좋은지 조사해 보세요.

2021-02-23 12:08 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/controllers/ProductController.java
> +    public Product update(@PathVariable Long id, @RequestBody @Valid Product product) {
`Product`같은 엔티티를 컨트롤러를 통해 HTTP 응답으로 유출하지 않는 것이 좋습니다. 전용의 POJO 객체 사용을 고려해 보시면 어떨까요?

2021-02-23 12:08 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/ProductServiceTest.java
> +            @DisplayName("장난감 목록을 반환한다 ")
```suggestion
            @DisplayName("장난감 목록을 반환한다")
```

2021-02-23 12:08 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/ProductServiceTest.java
> +        @DisplayName("등록된 장난감의 ID가 주어진다면")
코드에서는 `Product`인데 주석에서는 `장난감`이라 칭하고 있어요. 코드가 주석에 비해 더 추상화된 상태입니다. 이 갭을 완화할 수 있으면 좋겠어요.

2021-02-23 12:08 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/ProductServiceTest.java
> +                verify(productRepository).findById(1L);
`수정하고 반환한다`라고 테스트 메시지를 작성하셨는데요, `productService.updateProduct(1L, update);`를 보면 반환한 값은 검증하지 않고 있습니다.

2021-02-23 12:08 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/ProductServiceTest.java
> +                verify(productRepository).findById(100L);
예외가 던져진다는 사실만 검증하면 됩니다. 마지막의 `verify(productRepository).findById(100L);`는 테스트 메시지의 선언을 넘어선 검증 작업입니다.

2021-02-23 12:08 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/ProductServiceTest.java
> +            }
테스트 메시지는 `등록된 장난감의 ID가 주어진다면` 인데요, 실제로 준비하는 것은 ID가 아니라 `Product` 입니다.

2021-02-23 12:08 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/ProductServiceTest.java
> +}
파일 마지막에 개행 문자를 추가해 주세요.

2021-02-23 12:08 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/controllers/ProductControllerWebTest.java
> +                .willThrow(new ProductNotFoundException(100L));
`BDDMockito.given`을 많이 사용하고 계신데요, `@SpringBootTest` 애노테이션을 사용 중이라는 사실을 다시 상기해보시면 어떨까요?

2021-02-23 12:09 UTC, johngrib reviewed
오래간만입니다! 한 주간 같이 열심히 학습해 봅시다!

2021-02-24 12:31 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/ProductServiceTest.java
> +    void updateTest(ProductData update) {
커밋 메시지는 `Fix @DisplayName in ProductServiceTest` 인데요, 커밋 메시지와 관계 없는 내용도 추가되어 있습니다. 이제부턴 이런 작업도 깔끔히 관리할 수 있다면 좋을 거에요.

2021-02-24 12:31 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/domain/Product.java
> +@Setter
`@Setter`를 여기에 달아주면 모든 멤버에 setter 메소드가 생성됩니다. `id` 같은 값은 굳이 setter가 필요 없으므로 `@Setter`를 따로 지정해 주는 편이 좋을 거에요.

2021-02-24 12:31 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/domain/Product.java
> +    public void change(String name, String maker, Integer price) {
`change`보다 `update` 같은 이름은 어떨까요?

2021-02-25 12:18 UTC, yhyojoo commented on app/src/test/java/com/codesoom/assignment/application/ProductServiceTest.java
> +    void updateTest(ProductData update) {
네 앞으로 커밋할 때 그 부분에 대해서 좀 더 신경쓰도록 하겠습니다!

2021-02-25 12:30 UTC, johngrib reviewed
음 한동안은 한국어로 커밋 메시지를 작성해 보시면 어떨까요? 먼저 한국어로 좋은 커밋 메시지를 작성할 수 있게 되면, 그 다음에 영어로 커밋 메시지를 작성하는 연습을 해도 늦지 않을 것 같습니다.

2021-02-25 12:30 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/ProductServiceTest.java
> +import java.awt.*;
과제와 관계 없는 `import` 같습니다.

2021-02-25 12:38 UTC, johngrib requested changes
build.gradle 파일이 삭제되어 있어 프로젝트 빌드 구조가 망가져 있습니다. 이 파일을 살려주세요.

2021-02-27 12:15 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/UserNotFoundException.java
> +        super("User not found: " + id);
이 숫자가 `id`라는 것도 알려주는 문자열이면 더 좋을 것 같아요.

2021-02-27 12:15 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/application/ProductService.java
> +        this.mapper = dozerMapper;
lombok의 `@RequiredArgsConstructor`를 사용해 보시면 어떨까요?

2021-02-27 12:15 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/application/ProductService.java
> +        product.updateWith(mapper.map(productData, Product.class));
`updateWith` 메소드가 `Product`를 리턴하도록 수정해보면 어떨까요?

2021-02-27 12:15 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/UserServiceTest.java
> +import com.codesoom.assignment.ProductNotFoundException;
사용하지 않는 `import` 입니다.

2021-02-27 12:15 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/application/UserService.java
> +public class UserService {
서비스 클래스에는 JavaDoc 주석을 작성해 주세요.

2021-02-27 12:15 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/controllers/UserController.java
> +public class UserController {
컨트롤러에도 JavaDoc 주석을 작성해 주시면 좋겠습니다.

2021-02-27 12:15 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/domain/User.java
> +@Setter
`@Setter`가 여기에 있으면 `id`에도 setter가 생깁니다.

2021-02-27 12:15 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/ProductServiceTest.java
> +                product = productService.getProduct(1L);
등록된 상품의 id를 context scope에서 선언해주시면 좋겠습니다. 한편 `1L`이 하드코딩된 값이 아닌 논리적으로 도출된 값이면 더 좋겠어요.

2021-02-27 12:15 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/ProductServiceTest.java
> +            @DisplayName("해당 ID를 갖는 장난감을 삭제하고 반환한다")
여기에서도 `등록된 상품의 ID가 주어진다면`이라는 조건이 있는데 스코프 내에 `등록된 상품의 ID`가 정의되지 않았습니다.

2021-02-28 11:59 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/ProductNotFoundException.java
> +        super("Product ID not found: " + id);
좋습니다.

2021-02-28 11:59 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/domain/Product.java
> +import lombok.*;
`import *`에 주의해 주세요.

2021-02-28 11:59 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/ProductServiceTest.java
> +    private static final Long NOT_EXIST_ID = 123L;
분리는 괜찮은 아이디어지만 이 값에 논리적인 근거가 없다는 것이 아쉽습니다.

2021-02-28 11:59 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/application/ProductService.java
> +
불필요한 공백 라인입니다.

2021-02-28 11:59 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/application/ProductService.java
> +     * 새로운 상품을 등록합니다.
무엇을 리턴하는지도 적어주면 더 좋을 것 같아요.

2021-02-28 12:00 UTC, johngrib reviewed
한 주간 고생 많으셨습니다. 주간 회고를 작성해 공유해 주세요.

2021-03-02 12:23 UTC, merged

2021-03-02 12:23 UTC, johngrib commented
고생 많으셨습니다!